Fix build process
- Error (when use py.test):

ImportError: dynamic module does not define module export function (PyInit_sum_numbers)

- Solution:

Change build process to use "gosum" name for all generated *.so files. The only name that should be different is the module name, named "gosum_module.so"